services:
  postgres:
    image: postgres:15
    container_name: config-postgres
    restart: always
    environment:
      POSTGRES_DB: configdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
