apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer-service
  labels:
    role: indexer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      role: indexer-api
  template:
    metadata:
      labels:
        role: indexer-api
    spec:
      containers:
      - name: indexer-service
        image: commerceexperts/ocs-indexer-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8535
          name: indexer-api
        env:
        - name: ES_HOSTS
          value: "http://ocs-es-http:9200"
        - name: ES_AUTH_PW
          valueFrom:
            secretKeyRef:
              name: ocs-es-elastic-user
              key: elastic
        - name: ES_AUTH
          value: "elastic:$(ES_AUTH_PW)"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=90.0"
        resources:
          limits:
            memory: 3256Mi
          requests:
            memory: 3256Mi
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8535
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8535
