apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: indexer-ingress
  labels:
    role: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /indexer-api
        pathType: Prefix
        backend:
          service:
            name: indexer-api-service
            port:
              name: indexer-api