apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace where the ocs stack should be deployed
namespace: ocs-stack

# scale up search service here 
replicas:
- name: search-service
  count: 2

# change stage label here
commonLabels:
  component: ocs-stack
  stage: development

resources:
  - indexer-service.yaml
  - search-service.yaml
  - suggest-service.yaml
  - indexer-api.yaml
  - search-api.yaml
  - suggest-api.yaml
  - api-ingress.yaml
  - elasticsearch.yaml