apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: suggest-ingress
  labels:
    role: ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /suggest-api
        pathType: Prefix
        backend:
          service:
            name: suggest-api-service
            port:
              name: suggest-api