server:
  port: 8534
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/css
      - application/javascript
      - application/json
    
endpoints:
  prometheus:
    sensitive: true

spring:
  jackson:
    deserialization:
      fail_on_unknown_properties: false

ocs:
  connection-configuration:
    hosts: ${ES_HOSTS:http://localhost:9200}
    auth: ${ES_AUTH}
    
  default-tenant-config:
    facet-configuration:
      maxFacets: 12
      facets:
      - source-field: category
        label: Category
        order: 1
        excludeFromFacetLimit: true
      - source-field: brand
        label: Brand
        order: 2
        multi-select: true
        excludeFromFacetLimit: true
      - source-field: price
        label: Price
        order: 3
        meta-data:
          unit: "€"
        excludeFromFacetLimit: true
      - source-field: size
        label: Size
        order: 4
        meta-data:
          detail-links: 5 
        excludeFromFacetLimit: true
      - source-field: color
        label: Color
    scoring-configuration:
      boost-mode: avg
      score-mode: sum
      score-functions:
        - type: field_value_factor
          field: stock
          weight: 2.5
          options:
            missing: 0
    query-configuration:
      ean-search:
        strategy: "ConfigurableQuery"
        condition: 
          matchingRegex: "\\s*\\d{13}\\s*(\\s+\\d{13})*"
          maxTermCount: 42
        settings:
          operator: "OR"
          tieBreaker: 0
          analyzer: "whitespace"
          allowParallelSpellcheck: false
          acceptNoResult: true
        weightedFields:
          "[ean]": 1
      art-nr-search:
        strategy: "ConfigurableQuery"
        condition: 
          matchingRegex: "\\s*(\\d+\\w?\\d+\\s*)+"
          maxTermCount: 42
        settings:
          operator: "OR"
          tieBreaker: 0
          analyzer: "whitespace"
          allowParallelSpellcheck: false
          acceptNoResult: true
        weightedFields:
          "[artNr]": 2
          "[masterNr]": 1.5
          "[id]": 1
      # AND-match with optional shingles
      default-query:
        strategy: "ConfigurableQuery"
        condition: 
          minTermCount: 1
          maxTermCount: 10
        settings:
          operator: "AND"
          tieBreaker: 0.7
          multimatch_type: "CROSS_FIELDS"
          analyzer: "standard"
          isQueryWithShingles: true
          allowParallelSpellcheck: false
        weightedFields:
          "[title]": 3
          "[title.standard]": 2.5
          "[brand]": 2
          "[brand.standard]": 1.5
          "[category]": 2
          "[category.standard]": 1.7
      # pre fetch query
      standard-pre-fetch:
        strategy: "PredictionQuery"
        condition:
          minTermCount: 2
          maxTermCount: 10
        settings:
          analyzer: "standard"
          fallbackQuery: "relaxed-ngram-query"
        weightedFields:
          "[title]": 3
          "[title.standard]": 2.5
          "[brand]": 2
          "[brand.standard]": 1.5
          "[category]": 2
          "[category.standard]": 1.7
      # "real" fuzzy search for one-term search
      one-term-fuzzy-search:
        strategy: "ConfigurableQuery"
        condition:
          maxTermCount: 1
        settings:
          tieBreaker: 0.7
          acceptNoResult: false
          allowParallelSpellcheck: false
          fuzziness: "AUTO"
        weightedFields:
          "[title]": 3
          "[title.standard]": 2.5
          "[brand]": 2
          "[category]": 2
      # similar to a fuzzy query including decomposition
      relaxed-ngram-query:
        strategy: "NgramQueryBuilder"
        condition:
          maxTermCount: 10
        settings:
          minShouldMatch: "80%"
          tieBreaker: 0.2
        weightedFields:
          "[title]": 3
          "[title.standard]": 2.5
          "[brand]": 2
          "[category]": 2
      # for all queries with more then 10 words
      fallback-search:
        strategy: "ConfigurableQuery"
        condition:
          minTermCount: 10
        settings:
          analyzer: "standard"
          minShouldMatch: "75%"
        weightedFields:
          "[title]": 3
          "[title.standard]": 2.5
          "[brand]": 2
          "[brand.standard]": 1.5
          "[category]": 2
          "[category.standard]": 1.7

# index configuration MUST be the copy from indexer-service (although source-names could be removed
ocs:
  default-index-config:
    field-configuration:
      fields:
        id:
          name: id
          type: id
          usage:
            - result
          field-level: both
        masterNr:
          name: masterNr
          type: string
          source-names:
            - MasterArticleNumber
          usage:
            - result
          field-level: master
        artNr:
          name: artNr
          type: string
          source-names:
            - ArticleNumber
          usage:
            - result
          field-level: variant
        ean:
          name: ean
          source-names:
            - EAN
          usage:
            - search
            - result
        title:
          name: title
          type: string
          source-names: 
            - Title
            - product_name
            - ProductName
          usage:
            - search
            - result
            - sort
        brand:
          name: brand
          type: string
          source-names:
            - Brand
          value-delimiter: "|"
          usage:
            - search
            - facet
            - result
        price:
          name: price
          type: number
          source-names:
            - Price
          usage:
            - sort
            - result
            - facet
          field-level: both
        category:
          name: category
          type: category
          source-names:
            - Categories
            - CategoryPath
          usage:
            - result
            - facet
        shortDescription:
          name: shortDescription
          source-names:
            - ShortDescription
            - Short
          usage:
            - search
            - result
        description:
          name: description
          source-names:
            - Description
            - Text
          usage:
            - search
            - result
        productUrl:
          name: productUrl
          source-names:
            - ProduktURL
            - Deeplink
          usage:
            - result
          field-level: both
        imageUrl:
          name: imageUrl
          source-names:
            - ImageURL
          usage:
            - result
          field-level: both
        stock:
          name: stock
          source-names:
            - OnStock
            - StockLevel
          usage:
            - Score
            - Result