version: '3.5'

services:
  indexer:
    container_name: ocs_indexer
    image: commerceexperts/ocs-indexer-service:latest
    environment:
      - "ES_HOSTS=http://elasticsearch:9200"
      - "spring_profiles_active=preset,custom"
    ports:
      - 8535:8535
    volumes:
      - ./application.indexer-service.yml:/app/resources/application-custom.yml:ro
    depends_on:
      - elasticsearch
    networks:
      - ocs

  searcher:
    container_name: ocs_searcher
    image: commerceexperts/ocs-search-service:latest
    environment:
      - "ES_HOSTS=http://elasticsearch:9200"
      - "spring_profiles_active=preset,custom"
    ports:
      - 8534:8534
    volumes:
      - ./application.search-service.yml:/app/resources/application-custom.yml:ro
    depends_on:
      - elasticsearch
    networks:
      - ocs

  suggest:
    container_name: ocs_suggest
    image: commerceexperts/ocs-suggest-service:searchhub-latest
    ports:
      - 8081:8081
    depends_on:
      - elasticsearch
    networks:
      - ocs

  elasticsearch:
    container_name: ocs_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    environment:
      - "discovery.type=single-node"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/"
    networks:
      - ocs

  kibana:
    container_name: ocs_kibana
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - 5601:5601
    environment:
      - "ELASTICSEARCH_HOST=http://elasticsearch:9200/"
    links:
      - elasticsearch
    networks:
      - ocs
  
networks:
  ocs:
    name: ocs
    driver: bridge
