version: '3.5'

# extends the docker-compose.base.yml
#> docker compose -f docker-compose.base.yml -f docker-compose.local.yml

services:
  indexer:
    environment:
      - "spring_profiles_active=preset,custom"
    volumes:
      - ./application.indexer-service.yml:/app/resources/application-custom.yml:ro

  searcher:
    environment:
      - "spring_profiles_active=preset,custom"
    volumes:
      - ./application.search-service.yml:/app/resources/application-custom.yml:ro

