version: '3.5'

services:
  indexer:
    container_name: ocs_indexer
    image: commerceexperts/ocs-indexer-service:latest
    environment:
      - "ES_HOSTS=http://elasticsearch:9200"
      - "spring_profiles_active=preset,custom"
    ports:
      - 8535:8535
    volumes:
      - ./application.indexer-service.yml:/app/resources/application-custom.yml:ro
    depends_on:
      - elasticsearch
    networks:
      - ocs

  searcher:
    container_name: ocs_searcher
    image: commerceexperts/ocs-search-service:latest
    environment:
      - "ES_HOSTS=http://elasticsearch:9200"
      - "spring_profiles_active=preset,custom"
    ports:
      - 8534:8534
    volumes:
      - ./application.search-service.yml:/app/resources/application-custom.yml:ro
    depends_on:
      - elasticsearch
    networks:
      - ocs

  suggest:
    container_name: ocs_suggest
    image: commerceexperts/ocs-suggest-service:searchhub-latest
    ports:
      - 8081:8081
    depends_on:
      - elasticsearch
    networks:
      - ocs

  elasticsearch:
    container_name: ocs_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    # make sure the ./elasticsearch/docker-entrypoint-es.s file is executable
    volumes:
      - ./elasticsearch:/mnt
    entrypoint: 
      - /mnt/docker-entrypoint-es.sh
    ports:
      - 9200:9200
    environment:
      - "discovery.type=single-node"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=/https?://localhost(:[0-9]+)?/"
      - "ES_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,address=*:8000,suspend=n -Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - ocs

  kibana:
    container_name: ocs_kibana
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - 5601:5601
    environment:
      - "ELASTICSEARCH_HOST=http://elasticsearch:9200/"
    links:
      - elasticsearch
    networks:
      - ocs
  
networks:
  ocs:
    name: ocs
    driver: bridge
