server:
  port: 8535
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/css
      - application/javascript
      - application/json
    
endpoints:
  prometheus:
    sensitive: true

spring:
  jackson:
    deserialization:
      fail_on_unknown_properties: false

ocs:
  connection-configuration:
    hosts: ${ES_HOSTS:http://localhost:9200}
    auth: ${ES_AUTH}
    
  # default minimal configuration
  default-index-config:
    field-configuration:
      fields:
        id:
          name: id
          type: id
          usage:
            - Result
          field-level: both
        masterNr:
          name: masterNr
          type: string
          source-names:
            - MasterArticleNumber
          usage:
            - Search
            - Result
          field-level: master
        artNr:
          name: artNr
          type: string
          source-names:
            - ArticleNumber
          usage:
            - Search
            - Result
          field-level: variant
        ean:
          name: ean
          source-names:
            - EAN
          usage:
            - Search
            - Result
        title:
          name: title
          type: string
          source-names: 
            - Title
            - product_name
            - ProductName
          usage:
            - Search
            - Result
            - Sort
        brand:
          name: brand
          type: string
          source-names:
            - Brand
          value-delimiter: "|"
          usage:
            - Search
            - Facet
            - Result
        price:
          name: price
          type: number
          source-names:
            - Price
          usage:
            - Sort
            - Result
            - Facet
          field-level: variant
        category:
          name: category
          type: category
          source-names:
            - Categories
            - CategoryPath
          usage:
            - Result
            - Search
            - Facet
        shortDescription:
          name: shortDescription
          source-names:
            - ShortDescription
            - Short
          usage:
            - Search
            - Result
        description:
          name: description
          source-names:
            - Description
            - Text
          usage:
            - Search
            - Result
        productUrl:
          name: productUrl
          source-names:
            - ProduktURL
            - Deeplink
          usage:
            - Result
          field-level: both
        imageUrl:
          name: imageUrl
          source-names:
            - ImageURL
          usage:
            - Result
          field-level: both
        stock:
          name: stock
          source-names:
            - OnStock
            - StockLevel
          usage:
            - Score
            - Result
      dynamic-fields:
        - name: attribute
          type: number
          source-names:
            - .*
          usage:
            - Facet
        - name: attribute
          type: string
          source-names:
            - .*
          usage:
            - Facet
        - name: others
          source-names:
            - .*
          usage:
            - Result
