server:
  port: 8535
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/css
      - application/javascript
      - application/json
    
endpoints:
  prometheus:
    sensitive: true

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  metrics:
    enabled: true
    tags:
      application: "${spring.application.name}"

spring:
  cloud.config.enabled: false
  jackson.deserialization.fail_on_unknown_properties: false

ocs:
  connection-configuration:
    hosts: ${ES_HOSTS:http://localhost:9200}
    auth: ${ES_AUTH}
